[build]
  base = "direct-shift-connect"
  command = "npm run build"
  publish = "direct-shift-connect/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
