plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/anurag/statdoctor-github/direct-shift-connect/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/anurag/statdoctor-github/direct-shift-connect"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]